import { Injectable } from '@angular/core';
import { Invoice } from '../../../Entities/invoices';

@Injectable({
  providedIn: 'root',
})
export class InvoicesDatastoreService {
  constructor() {}

  list(): Invoice[] {
    return [
      {
        invoiceNumber: 'INV-001',
        date: '04.05.2024',
        description: 'Entwicklung der Plattform',
        type: 'Service',
        iwsNumber: 'IWS-9001',
        orderNumber: 'ORD-2024-01',
        orderName: 'Digitalisierung',
        value: 500,
        netAmount: 420,
        totalAmount: 920,
      },
      {
        invoiceNumber: 'INV-002',
        date: '05.05.2024',
        description: 'Beratung',
        type: 'Consulting',
        iwsNumber: 'IWS-9002',
        orderNumber: 'ORD-2024-02',
        orderName: 'Optimierung',
        value: 300,
        netAmount: 252,
        totalAmount: 552,
      },
      {
        invoiceNumber: 'INV-003',
        date: '10.05.2024',
        description: 'Software-Lizenz',
        type: 'Produkt',
        iwsNumber: 'IWS-9003',
        orderNumber: 'ORD-2024-03',
        orderName: 'Lizenzpaket A',
        value: 1000,
        netAmount: 840,
        totalAmount: 1840,
      },
      {
        invoiceNumber: 'INV-004',
        date: '10.06.2024',
        description: 'Netzwerkinstallation',
        type: 'Service',
        iwsNumber: 'IWS-9004',
        orderNumber: 'ORD-2024-04',
        orderName: 'IT Infrastruktur',
        value: 700,
        netAmount: 588,
        totalAmount: 1288,
      },
      {
        invoiceNumber: 'INV-005',
        date: '12.07.2024',
        description: 'IT-Schulung',
        type: 'Training',
        iwsNumber: 'IWS-9005',
        orderNumber: 'ORD-2024-05',
        orderName: 'Onboarding Schulung',
        value: 350,
        netAmount: 294,
        totalAmount: 644,
      },
      {
        invoiceNumber: 'INV-006',
        date: '17.08.2024',
        description: 'Cloud-Backup',
        type: 'Service',
        iwsNumber: 'IWS-9006',
        orderNumber: 'ORD-2024-06',
        orderName: 'Datensicherung',
        value: 420,
        netAmount: 352,
        totalAmount: 772,
      },
      {
        invoiceNumber: 'INV-007',
        date: '15.09.2024',
        description: 'Server-Migration',
        type: 'Consulting',
        iwsNumber: 'IWS-9007',
        orderNumber: 'ORD-2024-07',
        orderName: 'Migrationsprojekt',
        value: 1500,
        netAmount: 1260,
        totalAmount: 2760,
      },
      {
        invoiceNumber: 'INV-008',
        date: '17.08.2024',
        description: 'Hardware-Wartung',
        type: 'Service',
        iwsNumber: 'IWS-9008',
        orderNumber: 'ORD-2024-08',
        orderName: 'Serverpflege',
        value: 380,
        netAmount: 319,
        totalAmount: 699,
      },
      {
        invoiceNumber: 'INV-009',
        date: '17.10.2024',
        description: 'Benutzerverwaltung',
        type: 'Support',
        iwsNumber: 'IWS-9009',
        orderNumber: 'ORD-2024-09',
        orderName: 'Zugangskontrolle',
        value: 200,
        netAmount: 168,
        totalAmount: 368,
      },
      {
        invoiceNumber: 'INV-010',
        date: '18.08.2024',
        description: 'Mobile App Entwicklung',
        type: 'Projekt',
        iwsNumber: 'IWS-9010',
        orderNumber: 'ORD-2024-10',
        orderName: 'App Launch',
        value: 2100,
        netAmount: 1764,
        totalAmount: 3864,
      },
      {
        invoiceNumber: 'INV-011',
        date: '20.08.2024',
        description: 'SEO Optimierung',
        type: 'Consulting',
        iwsNumber: 'IWS-9011',
        orderNumber: 'ORD-2024-11',
        orderName: 'Marketing Boost',
        value: 950,
        netAmount: 798,
        totalAmount: 1748,
      },
    ];
  }
}
