name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.1' # Specific LTS version known to work with Angular 19
          cache: 'npm'
          
      - name: Clean npm cache
        run: npm cache clean --force
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli@19.2.5 --force
        
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install --package-lock-only
          npm install
        
      - name: Build Angular project
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          ng build --configuration=production --verbose
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: build-artifacts
          path: |
            dist/
            /tmp/ng-*
            
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IWS_MANAGER }}
          projectId: iws-manager
          channelId: pr-${{ github.event.pull_request.number }}