# .github/workflows/firebase-hosting-pull-request.yml

name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      # Descarga el código del repositorio
      - uses: actions/checkout@v4

      # Configura Node.js (ajusta la versión si es necesario)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instala Angular CLI globalmente
      - run: npm install -g @angular/cli

      # Instala dependencias y ejecuta build
      - run: npm ci && ng build

      # Despliegue de vista previa en Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_IWS_MANAGER }}
          projectId: iws-manager
